# Numpy - The fundamental package for scientific computing with Python<br>
Documentation Link: [https://www.numpy.org/](https://www.numpy.org/)

In [ ]:
import numpy as np

How can I check the version of Numpy that is installed? 

In [ ]:
np.version.version

'1.22.4'

## Migrating from list to Array! 

In [ ]:
lst=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar1=np.array(lst)
print(ar1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(ar1)

numpy.ndarray

In [ ]:
ar1.shape

(3, 3)

In [ ]:
ar1[1,2]

6

In [ ]:
np.transpose(ar1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar2=ar1.T
print(ar2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
ar2.reshape(2,2)

ValueError: ignored

In [ ]:
ar2.dtype

dtype('int64')

## Computation

In [ ]:
lst=[1,2,3]

In [ ]:
lst*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
lst+[6]

[1, 2, 3, 6]

In [ ]:
print ("ar1=\n", ar1,'\nar2=\n',ar2)
print (ar1+ar2)

ar1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
ar2=
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


In [ ]:
print ("ar1=\n", ar1,'\nar2=\n',ar2)
print (ar1+ar2*2)

ar1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
ar2=
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 3 10 17]
 [ 8 15 22]
 [13 20 27]]


In [ ]:
print ("ar1=\n", ar1,'\nar2=\n',ar2)
print (ar1/(ar2-1))

ar1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
ar2=
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[       inf 0.66666667 0.5       ]
 [4.         1.25       0.85714286]
 [3.5        1.6        1.125     ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [ ]:
print(ar1)
ar1.argmin(axis=1)
#max, argmax, argmin 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([0, 0, 0])

In [ ]:
#mean, var, std, sum
ar1.sum(axis=0)

array([12, 15, 18])

In [ ]:
#sin, cos, sqrt, log
np.log(ar1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

## Selection/Slicing

In [ ]:
ar2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar2[1,2]

8

In [ ]:
ar2[:,1]

array([4, 5, 6])

In [ ]:
ar3=ar2<=4
print(ar3)

[[ True  True False]
 [ True False False]
 [ True False False]]


In [ ]:
ar2[ar3]

array([1, 4, 2, 3])

In [ ]:
print(ar2)
ar2[ar2<=4]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([1, 4, 2, 3])

In [ ]:
ar2[ar2==4]

array([4])

In [ ]:
ar1[ar1<4]

array([1, 2, 3])

## Create Array with Numpy functions

In [ ]:
[i for i in range(1,11,1)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list(range(1,10,0.5))

TypeError: ignored

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros((10,5))+1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,2))-1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(1,9,10)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [ ]:
np.linspace(1,9,9)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.linspace(1,9,9).reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Broadcasting

In [ ]:
lst=[1,2,3]

In [ ]:
lst[0]=0

In [ ]:
lst

[0, 2, 3]

In [ ]:
lst[0:2]=0

TypeError: ignored

In [ ]:
ar1=np.arange(1,10).reshape(3,3)

In [ ]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar1[1:3,1:3]=0

In [ ]:
ar1

array([[1, 2, 3],
       [4, 0, 0],
       [7, 0, 0]])

In [ ]:
#broadcasting
ar1[0:2,0]=200

In [ ]:
ar1

array([[200,   2,   3],
       [200,   5,   6],
       [  7,   8,   9]])

## Avoid Aliasing

In [ ]:
AAR1=np.arange(1,10).reshape(3,3)
AAR1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
AAR1_Slice=AAR1[1:3,1:3]
AAR1_Slice

array([[5, 6],
       [8, 9]])

In [ ]:
AAR1_Slice[:,:]=0

In [ ]:
AAR1_Slice

array([[0, 0],
       [0, 0]])

In [ ]:
AAR1

array([[1, 2, 3],
       [4, 0, 0],
       [7, 0, 0]])

In [ ]:
AAR1=np.arange(1,10).reshape(3,3)
AAR1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
AAR1_Slice=AAR1.copy()[1:3,1:3]

In [ ]:
AAR1_Slice

array([[5, 6],
       [8, 9]])

In [ ]:
AAR1_Slice[:]=0
AAR1_Slice

array([[0, 0],
       [0, 0]])

In [ ]:
AAR1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
AAR1_Slice

array([[0, 0],
       [0, 0]])

## Random

In [ ]:
#does include 0 but not 1
np.random.rand(6).reshape(2,3)


array([[0.86794949, 0.47881375, 0.28332454],
       [0.88895316, 0.21106924, 0.04288753]])

In [ ]:
np.random.rand(5,2)*10

array([[1.09527108, 2.11573456],
       [7.89758619, 1.73679168],
       [6.99674363, 6.72208115],
       [6.32792498, 0.3171238 ],
       [8.83671058, 1.56720321]])

In [ ]:
np.random.randint(1,1000,(5,5))

array([[825, 433, 929, 466, 670],
       [184,  72, 579, 429, 879],
       [414,  92, 250,  66, 640],
       [ 76, 431,  59, 458, 993],
       [170, 256, 953, 442, 685]])

In [ ]:
np.random.randn(10,2)

array([[ 0.37196757,  0.35975395],
       [-0.14039647, -0.44373851],
       [ 0.56877016,  0.53848877],
       [ 1.31557418,  1.4789783 ],
       [ 0.22142626, -1.11789416],
       [-0.18499993, -0.43118745],
       [ 0.14253625, -1.49639345],
       [ 0.30687456, -0.04634723],
       [ 0.41714428, -0.60377052],
       [ 0.68596725,  0.85997379]])

In [ ]:
np.random.seed(6)
np.random.randint(1,100,(5,2))

array([[11, 74],
       [85, 80],
       [81, 63],
       [26,  2],
       [76, 78]])